apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name         tail
        Path         /var/log/app/*.log
        Tag          app.*
        DB           /var/log/app/fluentbit.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [OUTPUT]
        Name         stdout
        Match        app.*
  parsers.conf: |
    [PARSER]
        Name         json
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S
